name: Building(CMake)

on:
  push:
    branches: [ qt6_2 ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  workflow_dispatch:

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  linux-build:
    name: ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source code
        uses: actions/checkout@v3
        
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.*'
          modules: 'all'
          
      - name: Install Dependencies
        run: |
          sudo apt-get -y -qq update
          sudo apt-get -y --no-install-recommends install \
            cmake \
            extra-cmake-modules \
            libvulkan-dev \
            build-essential 

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake $GITHUB_WORKSPACE -DUSE_QT6=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE
      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: ${{runner.workspace}}/build/*
